### ISSUE TITLE
Mote explodes when spec functions take arguments

### ISSUE THREAD

**Issue by garybernhardt** [garybernhardt/mote#3]
Imported from BitBucket:

If you accidentally add a "self" argument to a spec function, Mote does something like this:

```
Traceback (most recent call last):
  File "/Users/grb/proj/expecter_gadget/env/bin/mote", line 8, in <module>
    load_entry_point('mote==0.1', 'console_scripts', 'mote')()
  File "/Users/grb/proj/mote/repo-rewrite/mote/runner.py", line 24, in main
    suite = SpecSuite(modules)
  File "/Users/grb/proj/mote/repo-rewrite/mote/suite.py", line 13, in __init__
    for ctx in self._contexts_from_module(module_contents.values())]
  File "/Users/grb/proj/mote/repo-rewrite/mote/suite.py", line 20, in _contexts_from_module
    and value.__name__.startswith('describe_')]
  File "/Users/grb/proj/mote/repo-rewrite/mote/suite.py", line 30, in __init__
    self.children = self._collect_children()
  File "/Users/grb/proj/mote/repo-rewrite/mote/suite.py", line 86, in _collect_children
    return [Context(function, self) for function in local_functions]
  File "/Users/grb/proj/mote/repo-rewrite/mote/suite.py", line 30, in __init__
    self.children = self._collect_children()
  File "/Users/grb/proj/mote/repo-rewrite/mote/suite.py", line 86, in _collect_children
    return [Context(function, self) for function in local_functions]
  File "/Users/grb/proj/mote/repo-rewrite/mote/suite.py", line 30, in __init__
    self.children = self._collect_children()
  File "/Users/grb/proj/mote/repo-rewrite/mote/suite.py", line 81, in _collect_children
    self.failure = Failure(sys.exc_info())
  File "/Users/grb/proj/mote/repo-rewrite/mote/suite.py", line 92, in __init__
    self.exc_traceback = self._remove_mote_from_traceback(exc_traceback)
  File "/Users/grb/proj/mote/repo-rewrite/mote/suite.py", line 106, in _remove_mote_from_traceback
    frame = traceback.tb_frame
AttributeError: 'NoneType' object has no attribute 'tb_frame'
```

**Comment by garybernhardt** [comment]
Closing all issues and archiving repo.
